### ISSUE TITLE
Quantisation may not work in Python 3

### ISSUE THREAD

**Issue by IvanWeiYR** [keunwoochoi/LSTMetallica#10]
For the line:
```
note.c_tick = ((note.c_tick+minimum_ppq/2)/minimum_ppq)* minimum_ppq
```
It will work in python 2 but not work in python3.

For example, if note.c_tick = 500 and minimum_ppq = 120, python 2 will produce 480, but python 3 will produce 560. This may cause problems for creating the binary string. 

Maybe you can add this into the readme. Great project anyway.

**Comment by keunwoochoi** [comment]
Hi, you must be right - I was using python 2 back then.
